environment:
  unity_install_uri: https://netstorage.unity3d.com/unity/a9f86dcd79df/Windows64EditorInstaller/UnitySetup64-2017.3.0f3.exe
  unity_license_key:
    secure: fEzK1w0OoekfLzGUKkLOCqUSCUNLXRBgpiFwSzd/5p8=
  unity_license_user:
    secure: YqXgQdqvtk2cQcXQrQdxowpkcD3D0ZVc1A3vne57ySgsp7U/F+RDPBWR+di4h0unuvsVDRNEicb+J07AIgz1ZQ==
  unity_license_pass:
    secure: 9JAa44lLTlBFsePdA7khJg==
install:
  - ps: |
      Invoke-WebRequest -Uri $env:unity_install_uri -OutFile "UnitySetup.exe"
      .\UnitySetup.exe /S /D=c:\UnityInstall
      while ($(ps | grep UnitySetup | measure).count -gt 0) { sleep 10; ps | grep UnitySetup; }
      c:\UnityInstall\Editor\Unity.exe -batchmode -nographics -silent-crashes -logFile c:\unity.log -serial $env:unity_license_key -username '$env:unity_license_user' -password '$env:unity_license_pass' -quit
      while ($(ps | grep Unity | measure).count -gt 0) { sleep 10; ps | grep Unity; }
      type c:\unity.log
build_script:
  - ps: |
      echo Running Standalone PC Build
      c:\UnityInstall\Editor\Unity.exe -batchmode -force-free -nographics -silent-crashes -logFile c:\unity.log -projectPath $env:APPVEYOR_BUILD_FOLDER -buildWindowsPlayer c:\Artifacts\Build.exe -quit
      while ($(ps | grep Unity | measure).count -gt 0) { sleep 10; ps | grep Unity; }
      if (![System.IO.File]::Exists('c:\Artifacts\Build.exe')) { echo $LASTEXITCODE; type c:\unity.log; exit -1; }
test_script:
  - ps: |
      echo Running Editor Tests
      c:\UnityInstall\Editor\Unity.exe -batchmode -force-free -nographics -silent-crashes -logFile c:\unity.log -projectPath $env:APPVEYOR_BUILD_FOLDER -runEditorTests -editorTestsResultFile c:\tests.xml -quit
      if (![System.IO.File]::Exists('c:\tests.xml')) { type c:\unity.log; exit -1; }
      [xml]$tests = Get-Content c:\tests.xml
      echo $tests
